
version: '3.4'

services:
  qbithelper:
    image: qbithelper
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
